spring:
  datasource:
    type: org.apache.tomcat.jdbc.pool.DataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://52.79.217.148:3306/coawesome?autoReconnect=true&useSSL=false
    username: master
    password: coawesome123!

mybatis:
   config-location: classpath:mybatis-config.xml